kind: Service
apiVersion: v1
metadata:
  name: weatherapp-service
spec:
  selector:
    app: weatherapp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080
    targetPort: weather-port
  type: NodePort